# Generated by Django 5.1.1 on 2024-09-22 13:56

import django.core.validators
import healthpal_patients.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, validators=[django.core.validators.MinLengthValidator(limit_value=2, message='Name should have at least 2 symbols'), django.core.validators.RegexValidator(message='Invalid name format. Use letters, spaces, hyphens, or apostrophes. Start and end with letters.', regex="^[A-Za-zÀ-ÿ]+([ '-][A-Za-zÀ-ÿ]+)*$")])),
                ('gender', models.CharField(choices=[('m', 'male'), ('f', 'female')], max_length=1)),
                ('birthdate', models.DateField(validators=[django.core.validators.MaxValueValidator(limit_value=healthpal_patients.models.get_timezone_now_date, message='Birthdate cannot be in the future.'), django.core.validators.MinValueValidator(limit_value=healthpal_patients.models.get_age_threshold, message='Birthdate cannot be more than 120 years ago.')])),
                ('phone', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='Invalid phone format. Use digits only.', regex='^[0-9]+$')])),
                ('address', models.CharField(validators=[django.core.validators.RegexValidator(message='Invalid Google Place ID format. Use digits, letters, underscores, or hyphens.', regex='^[A-Za-z0-9_\\-]+$')])),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('full_name', 'birthdate'), name='unique_name_birthdate')],
            },
        ),
    ]
