# Generated by Django 5.1.1 on 2024-09-20 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField()),
                ('last_name', models.CharField()),
                ('gender', models.CharField(choices=[('m', 'male'), ('f', 'female')])),
                ('birthdate', models.DateField()),
                ('phone', models.CharField()),
                ('address', models.CharField()),
            ],
        ),
    ]
