# Generated by Django 5.1.1 on 2024-09-23 13:28

import datetime
import django.core.validators
import django.db.models.deletion
import healthpal_patients.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthpal_patients', '0002_alter_patient_birthdate'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='assigned_clinician',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='patient',
            name='address',
            field=models.CharField(validators=[django.core.validators.RegexValidator(message='Invalid Google Place ID format. Use digits, letters, underscores, or hyphens.', regex='^[A-Za-z0-9_-]+$')]),
        ),
        migrations.AlterField(
            model_name='patient',
            name='birthdate',
            field=models.DateField(validators=[django.core.validators.MaxValueValidator(limit_value=datetime.date(2024, 9, 23), message='Birthdate cannot be in the future.'), django.core.validators.MinValueValidator(limit_value=healthpal_patients.models.get_age_threshold, message='Birthdate cannot be more than 120 years ago.')]),
        ),
        migrations.AlterField(
            model_name='patient',
            name='full_name',
            field=models.CharField(max_length=255, validators=[django.core.validators.MinLengthValidator(limit_value=2, message='Name should have at least 2 symbols.'), django.core.validators.RegexValidator(message='Invalid name format. Use letters, spaces, hyphens, or apostrophes. Start and end with letters.', regex="^[A-Za-zÀ-ÿ]+([ '-][A-Za-zÀ-ÿ]+)*$")]),
        ),
    ]
