# Generated by Django 5.1.1 on 2024-09-24 14:11

import datetime
import django.core.validators
import healthpal_patients.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthpal_patients', '0004_alter_patient_assigned_clinician'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='birthdate',
            field=models.DateField(validators=[django.core.validators.MaxValueValidator(limit_value=datetime.date(2024, 9, 24), message='Birthdate cannot be in the future.'), django.core.validators.MinValueValidator(limit_value=healthpal_patients.models.get_age_threshold, message='Birthdate cannot be more than 120 years ago.')]),
        ),
    ]
