# Generated by Django 5.1.1 on 2024-09-21 08:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('healthpal_patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField()),
                ('datetime', models.DateTimeField()),
                ('score', models.PositiveSmallIntegerField()),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='healthpal_patients.patient')),
            ],
        ),
        migrations.CreateModel(
            name='AssessmentQnARound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField()),
                ('answer', models.CharField()),
                ('patient_assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qna_rounds', to='healthpal_assessments.patientassessment')),
            ],
        ),
    ]
