# Generated by Django 5.1.1 on 2024-09-22 15:50

import datetime
import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthpal_assessments', '0001_initial'),
        ('healthpal_patients', '0002_alter_patient_birthdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientassessment',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, validators=[django.core.validators.MaxValueValidator(limit_value=datetime.date(2024, 9, 22), message='Assessment date cannot be in the future.')]),
        ),
        migrations.AlterField(
            model_name='patientassessment',
            name='score',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(limit_value=100, message='Score cannot be greater than 100.')]),
        ),
        migrations.AlterField(
            model_name='patientassessment',
            name='type',
            field=models.CharField(max_length=64, validators=[django.core.validators.RegexValidator(message='Invalid type format. Use letters, numbers, spaces, or hyphens. Start and end with letters or numbers.', regex='^[A-Za-z0-9]+([ -][A-Za-z0-9]+)*$')]),
        ),
        migrations.AddConstraint(
            model_name='assessmentqnaround',
            constraint=models.UniqueConstraint(fields=('question', 'patient_assessment'), name='unique_question_assessment'),
        ),
        migrations.AddConstraint(
            model_name='patientassessment',
            constraint=models.UniqueConstraint(fields=('patient', 'date', 'type'), name='unique_patient_date_type'),
        ),
    ]
