# Generated by Django 5.1.1 on 2024-09-23 13:28

import datetime
import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthpal_assessments', '0002_alter_patientassessment_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientassessment',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, validators=[django.core.validators.MaxValueValidator(limit_value=datetime.date(2024, 9, 23), message='Assessment date cannot be in the future.')]),
        ),
    ]
